In [1]:
import tensorflow as tf

In [3]:
a = tf.constant([9, 8, 7], name = 'a')

In [4]:
b = tf.constant([1, 2, 3], name = 'b')

In [13]:
soma = a + b

In [6]:
type(a)

tensorflow.python.framework.ops.Tensor

In [7]:
print(a)

Tensor("a:0", shape=(3,), dtype=int32)


In [8]:
with tf.Session() as sess:

SyntaxError: unexpected EOF while parsing (<ipython-input-8-25c51a2f7f91>, line 1)

In [14]:
with tf.Session() as sess:
    print(sess.run(soma))

[10 10 10]


In [16]:
a1 = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'a1')

In [17]:
type(a1)

tensorflow.python.framework.ops.Tensor

In [18]:
print(a1)

Tensor("a1_1:0", shape=(2, 3), dtype=int32)


In [19]:
a1.shape

TensorShape([Dimension(2), Dimension(3)])

In [20]:
b1 = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'b1')

In [21]:
soma1 = tf.add(a1, b1)

In [25]:
with tf.Session() as sess:
    print(sess.run(soma1))

[[ 2  4  6]
 [ 8 10 12]]


In [27]:
soma2 = tf.multiply(a1, b1)

In [28]:
with tf.Session() as sess:
    print(sess.run(soma2))

[[ 1  4  9]
 [16 25 36]]


In [34]:
a2 = tf.constant([[1, 2, 3], [4,5,6]])
b2 = tf.constant([[1], [2]])
soma3 = tf.add(a2, b2)

In [36]:
with tf.Session() as sess:
    print(sess.run(a2))
    print('\n')
    print(sess.run(b2))
    print(sess.run(soma3))

[[1 2 3]
 [4 5 6]]


[[1]
 [2]]
[[2 3 4]
 [6 7 8]]
